### ISSUE TITLE
firefox and chrome browsers to centos7-run

### ISSUE THREAD

**Issue by astoker-test** [smanders/buildpro#21]
Can we add the following to the centos7-run:

Firefox 78.7.0
Chrome 88 (If you can get it, Chrome does make it difficult to find old versions and if it's not available then the latest stable version is ok)

Based on emails 6/2/2021

**Comment by smanders** [comment]
firefox

https://support.mozilla.org/en-US/kb/install-older-version-firefox
https://ftp.mozilla.org/pub/firefox/releases/
https://ftp.mozilla.org/pub/firefox/releases/78.7.0esr/linux-x86_64/en-US/
https://www.cyberciti.biz/faq/howto-install-firefox-15-0-tar-bz2-in-linux/

runtime container needs bzip2 to extract firefox .tar.bz2 file
```
sudo yum install bzip2
```

install firefox in container with
```
sudo wget https://ftp.mozilla.org/pub/firefox/releases/78.7.0esr/linux-x86_64/en-US/firefox-78.7.0esr.tar.bz2 -qO- | sudo tar -xj -C /opt
```

try running it
```
$ /opt/firefox/firefox
XPCOMGlueLoad error for file /opt/firefox/libmozgtk.so:
libgtk-3.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```
install gtk3
```
sudo yum install gtk3.x86_64
```

try running it
```
$ /opt/firefox/firefox
XPCOMGlueLoad error for file /opt/firefox/libxul.so:
libXt.so.6: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```
install libXt
```
sudo yum install libXt.x86_64
```

firefox now launches successfully

looks like installing these dependencies is a common issue https://programmerah.com/619libgtk-3-so-0-or-libxt-so-6-cannot-open-shared-object-file-no-such-file-or-directory-9490/

put link to firefox in PATH so user can just type `firefox` to launch it
```
sudo ln -s /opt/firefox/firefox /usr/local/bin/firefox
```

launch firefox so you don't see stdout and stderr
```
firefox 1>/dev/null 2>&1 &
```

**Comment by smanders** [comment]
@astoker-test someone can test out the centos7-run container, by changing the VANTAGE centos7-run.dockerfile
```diff
diff --git a/.devcontainer/centos7-run.dockerfile b/.devcontainer/centos7-run.dockerfile
index a4527d1..6d59342 100644
--- a/.devcontainer/centos7-run.dockerfile
+++ b/.devcontainer/centos7-run.dockerfile
@@ -1,4 +1,4 @@
-FROM ghcr.io/smanders/buildpro/centos7-run:21.13
+FROM ghcr.io/smanders/buildpro/centos7-run:latest
 LABEL maintainer="smanders"
 LABEL org.opencontainers.image.source https://github.com/smanders/buildpro
 SHELL ["/bin/bash", "-c"]
```
you just won't want to stay on (commit/submit) the `latest` tag because it will be in state of flux

**Comment by smanders** [comment]
chrome

installing chrome in a docker image was a little more tricky...

basic "How to Install Google Chrome Web Browser on CentOS 7"
* https://linuxize.com/post/how-to-install-google-chrome-web-browser-on-centos-7/
* https://www.cyberciti.biz/faq/howto-install-google-chrome-on-redhat-rhel-fedora-centos-linux/
```
wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
sudo yum localinstall google-chrome-stable_current_x86_64.rpm
google-chrome &
```

"How to download and install chrome browser with specific version in terminal?"
https://unix.stackexchange.com/questions/371981/how-to-download-and-install-chrome-browser-with-specific-version-in-terminal
```
yum install -y https://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-${GOOGLE_CHROME_VERSION}-1.x86_64.rpm
```
how to find valid `GOOGLE_CHROME_VERSION` numbers
* find available versions from looking at Ubuntu releases
* https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable
* https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable?id=202706&page=6
  * latest 88 release is  `88.0.4324.182-1`
  * tested that I could download it: `wget https://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-88.0.4324.182-1.x86_64.rpm`

but as soon as I installed this specific version it was *always* updated to the latest stable release, until I found...

Manage Chrome browser updates (Linux)
https://support.google.com/chrome/a/answer/9052345
add `repo_add_once=false` to `/etc/default/google-chrome` before installing Chrome browser

**Comment by smanders** [comment]
correct version is installed, but fails to launch
```
smanders@vantage-run:/
$ google-chrome --version
Google Chrome 88.0.4324.182

smanders@vantage-run:/
$ google-chrome &
[1] 50

smanders@vantage-run:/
$ Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted

[1]+  Trace/breakpoint trap   (core dumped) google-chrome

```

**Comment by astoker-test** [comment]
Thanks @smanders! It appears to be working for both firefox and chrome.  We do only use them in headless mode for the automated tests so perhaps that is why I'm not seeing the same error you were seeing with chrome, it may be related to the GUI

**Comment by smanders** [comment]
I found an article "Launching Google Chrome on Docker container"
https://thespecguy.medium.com/launching-google-chrome-on-docker-container-a7dc2ba2d5
that shows a Dockerfile ENTRYPOINT with the following
```
ENTRYPOINT ["google-chrome","--no-sandbox"]
```
and when I launch google-chrome with the `--no-sandbox` option, the GUI appears to work! I also added the arguments so that you don't see stdout and stderr in the terminal
```
google-chrome --no-sandbox 1>/dev/null 2>&1 &
```
when the chrome browser GUI is displayed, I see a dailog dismissable by clicking the `X` (I don't select the `Reinstall Chrome` button)
```
Can't update Chrome
Chrome couldn't update to the
latest version, so you're missing
out on new features and security
fixes.
```
I also see a banner in the browser, which I can also dismiss by clicking the `X`
```
You are using an unsupported command-line flag: --no-sandbox. Stability and security will suffer.
```
I went to espn.com and it loaded fine

**Comment by smanders** [comment]
Another article with information "Running Chrome in a Docker container" https://medium.com/dot-debug/running-chrome-in-a-docker-container-a55e7f4da4a8 (that I didn't seem to need to get things working -- likely because the buildpro images and denv.sh script, etc, already support X forwarding) and a similar article https://www.mattzeunert.com/2018/07/21/running-headful-chrome-on-ubuntu-server.html

And an article and github repo
* https://www.tekfik.com/kb/devops/google-chrome-on-docker-container
* https://github.com/TekFik/chrome-web

**Comment by smanders** [comment]
this support will be part of the buildpro 21.14 image... let me know how urgent it is to release this, or if can wait until other features are ready (offline docker images)

**Comment by smanders** [comment]
email that was referenced in the original description

>From: Austin Stoker
Sent: Tuesday, June 1, 2021 3:02 PM
To: Paul Bowen
Subject: Browser Versions for SWAT, do you approve?
> 
>Hi Paul,
>
>For the containers we can, and want to, lock in a browser version, I propose we go with:
Firefox 78.7.0
Chrome 88 (If smanders can get it, Chrome does make it difficult to find old versions and if it's not available then the latest stable version will be ok)
>
>Based on this info I got from Mike Winn:
> 
>
>VIP-MC – Sent patch out to sites today
>* Mozilla Firefox: 78.10.1
>* Does not contain Google Chrome on system
>
>VIP-C (RGS) – Will be fielded later in June
>* Mozilla Firefox: 78.7.0
>* Google Chrome Enterprise: 88.0.4324.150
>
>VIP-C (DCGS) – Will finish fieldings end of June
>* Mozilla Firefox: 68.4.1
>* Google Chrome Enterprise: 79.0.3945.130
> 
>Do you approve of this choice?
Austin

**Comment by smanders** [comment]
recent email
>From: Brett Francis
Date: Monday, December 20, 2021 at 5:16 PM
Subject: VANTAGE Minimum Browser Versions
>
>We are updating the minimum browser versions for VANTAGE 3.66 to the following
Google Chrome                94.0.4606.81
Mozilla Firefox                  78.15.0

**Comment by smanders** [comment]
verified
```
smanders@vantage-run:/
$ which firefox
/usr/local/bin/firefox

smanders@vantage-run:/
$ firefox --version
Mozilla Firefox 78.15.0esr

smanders@vantage-run:/
$ which google-chrome
/usr/bin/google-chrome

smanders@vantage-run:/
$ google-chrome --version
Google Chrome 94.0.4606.81 

smanders@vantage-run:/
$ firefox 1>/dev/null 2>&1 &
[1] 58

smanders@vantage-run:/
$ google-chrome --no-sandbox 1>/dev/null 2>&1 &
[1] 349
```
completed with commit referenced above
